[package]
name = "rype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21"
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
rand = "0.8.0"
